#!/usr/bin/env python

import sys
from scapy.all import *

def banner():
        print "********************************************"
        print "         Clinet Probe Request to Acess point (AP) "
        print "*********************************************"

client=set()
def packethandler(pkt):
        if pkt.haslayer(Dot11ProbeReq ):
                if (pkt.info>0):
                        previous=pkt.addr2 +"------"+ pkt.addr3+"------"+pkt.info
                        if previous not in client:
                                client.add(previous)
                                print "New client Pronbe :"+pkt.addr2 +" " +pkt.addr3 +" "  + pkt.info
                        print "  -----Client Probe table ---"
                        for probe in client:
                                [clients,AP,ssid]=probe.split("----")
                                       print clients ,AP,ssid
                        print "-------------------------------"

           
banner()
sniff(iface=sys.argv[1],count=int(sys.argv[2]),prn=packethandler)
                                             
